config/routes.rb
Rails.application.routes.draw do
  get "/" ,to: "servers#index"
  resources :servers, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/server.rb
class Server < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  def index
    @servers = Server.all
  end

  def new
    @server = Server.new
  end

  def create
    @server = Server.new(server_params)
    if @server.save
      redirect_to action: :index
    else
      render :new
    end
  end

  private
  def server_params
    params.require(:server).permit(:ip_address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/servers/index.html.erb
<div>
  サーバーの一覧ページです
</div>
<% @servers.each do |server| %>
  <div><%= server.ip_address %><div>
<% end %>
<div>
  <%= link_to "新しいサーバーを登録する", new_server_path %>
</div>

app/views/servers/new.html.erb
<div>サーバーの登録ページです</div>
<%= form_with model:@server do |f| %>
  <%= f.label :ip_address, "登録するサーバーのIPアドレスを入力してください" %>
  <%= f.text_field :ip_address %>
  <%= f.submit "サーバーを登録する" %>
<% end %>